<?php

namespace Nextbyte\Tests\Courier;

use Illuminate\Foundation\Bootstrap\LoadEnvironmentVariables;
use Nextbyte\Courier\CourierManager;
use Nextbyte\Courier\CourierServiceProvider;
use Nextbyte\Courier\Facades\Courier;
use Orchestra\Testbench\TestCase as OrchestraTestCase;

abstract class TestCase extends OrchestraTestCase
{
    protected $loadEnvironmentVariables = true;

    protected function setUp(): void
    {
        if (file_exists(dirname(__DIR__) . '/.env')) {
            (\Dotenv\Dotenv::createImmutable(dirname(__DIR__), '.env'))->load();
        }

        parent::setUp(); // TODO: Change the autogenerated stub
    }

    protected function getEnvironmentSetUp($app)
    {
        // make sure, our .env file is loaded
        $app->useEnvironmentPath(__DIR__.'/..');
        $app->bootstrapWith([LoadEnvironmentVariables::class]);

        parent::getEnvironmentSetUp($app);
    }

    /**
     * Get package providers.
     *
     * @param  \Illuminate\Foundation\Application  $app
     *
     * @return array
     */
    protected function getPackageProviders($app)
    {
        return [
            CourierServiceProvider::class,
        ];
    }

    /**
     * @param string $driver
     * @return \Nextbyte\Courier\Contracts\Courier
     */
    protected function makeDriver($driver)
    {
        return Courier::vendor($driver);
    }

//    protected function getEnvironmentSetUp($app)
//    {
//        Cashier::useCustomerModel(User::class);
//    }
//
//    protected function getPackageProviders($app)
//    {
//        return [CashierServiceProvider::class];
//    }
}
